runtime: nodejs20

handlers:
  # Serve the firebase_credentials.json file
  - url: /firebase_key/firebase_credentials.json
    static_files: firebase_key/firebase_credentials.json
    upload: firebase_key/firebase_credentials.json

# Optional configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
